#!/bin/sh
set -e

##
# localbase=$(libexec/dirname /usr/local/share/emacs/ 2)

##
# variables
path=$(realpath "$1")
depth=$2
i=0

##
# main
while [ "${i}" -lt "${depth:-1}" ]; do
  path=$(dirname "${path}")
  # shellcheck disable=SC2003
  i=$(expr "${i}" + 1)
done
echo "${path}"
