#!/bin/sh
set -e

##
# variables
user="_blocks"
localbase=$("$(dirname "$0")"/dirname "$0" 3)
libexec="${localbase}"/libexec/blocks+cron
homedir="${localbase}"/share/blocks+cron/home/"${user}"

##
# functions
printok() {
    "${libexec}"/utils/printok "${1}"
}

printerr() {
    "${libexec}"/utils/printerr "${1}"
}

##
# main
# shellcheck disable=SC1091
if ! id "${user}" > /dev/null 2>&1; then
    if [ "$(uname)" = "OpenBSD" ]; then
        useradd \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            "${user}"
        printok "create user ${user}"
    elif [ "$(uname)" = "FreeBSD" ]; then
        pw useradd \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            -n "${user}"
        printok "create user ${user}"
    else
        printerr "$(uname) is not supported"
        exit 1
    fi
else
    printok "${user} user exists"
    if [ ! -e "/home/${user}" ]; then
        mkdir /home/${user}
    fi
    find "${homedir}" \
          -mindepth 1 \
          -maxdepth 1 \
          -exec cp -Rf {} /home/${user}/ \;
fi

find /home/"${user}" \
    -type d \
    -exec chown _blocks:_blocks {} \; \
    -exec chmod u=rwx,g=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -exec chown _blocks:_blocks {} \; \
    -exec chmod u=rw,g=r,o= {} \;
find /home/"${user}"/.local/libexec \
    -type f \
    -exec chown root:_blocks {} \; \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}"/bin \
    -type f \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -name .gitkeep \
    -exec rm {} \;
printok "setup /home/_blocks/"
