#!/bin/sh -e

##
# variables
localbase=$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")
share="${localbase}"/share/blocks+cron
doas=$(cat "${share}"/doas.conf)
file=""

##
# main
# shellcheck disable=SC1091
if [ "$(uname)" = "OpenBSD" ]; then
    file="/etc/doas.conf"
elif [ "$(uname)" = "FreeBSD" ]; then
    file="${LOCALBASE:-/usr/local}/etc/doas.conf"
else
    echo "[x] $(uname) is not supported"
    exit 1
fi

if grep -F "^${doas}$" "${file}" > /dev/null 2>&1; then
    echo "[-] ${file} remains unchanged"
else
    echo "${doas}" >> "${file}"
    echo "[-] ${file} has been changed. Please review the changes"
fi
