#!/bin/sh -e

##
# variables
user="_blocks"
mode="u=rwx,g=rx,o="
localbase=$(dirname $(dirname $(dirname $(realpath "$0"))))
libexec="${localbase}"/libexec/blocks+cron
homedir="${localbase}"/share/blocks+cron/home/"${user}"

##
# main
. "${libexec}"/platform.sh
if ! id "${user}" > /dev/null 2>&1; then
    if isOpenBSD; then
        useradd \
            -M "${mode}" \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            "${user}"
        echo "[-] The ${user} user and group have been created"
    elif isFreeBSD; then
        pw useradd \
            -M "${mode}" \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            -n "${user}"
        echo "[-] The ${user} user and group have been created"
    else
        echo "[-] Platform is not supported"
        exit 1
    fi
else
    cp -Rfv "${homedir}"/* /home/${user}/
    cp -Rfv "${homedir}"/.local /home/${user}/
    echo "[-] The ${user} user exists"
fi

set -x
find /home/"${user}" \
    -type d \
    -exec chmod u=rwx,g=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -exec chmod u=rw,g=r,o= {} \;
find /home/"${user}"/.local/libexec \
    -type f \
    -exec chown root:_blocks {} \; \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}"/bin \
    -type f \
    -exec chown _blocks:_blocks {} \; \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -name .gitkeep \
    -exec rm {} \;
set +x
