#!/bin/sh -e

##
# variables
user="_blocks"
localbase=$("$(dirname "$0")"/dirname "$0" 3)
share="${localbase}"/share/blocks+cron
crontab="/var/cron/tabs/${user}"
allowfile=""

##
# main
# shellcheck disable=SC1091
if [ "$(uname)" = "OpenBSD" ]; then
    allowfile="/var/cron/cron.allow"
elif [ "$(uname)" = "FreeBSD" ]; then
    allowfile="/var/cron/allow"
else
    echo "[x] $(uname) is not supported"
    exit 1
fi

if [ -e "${allowfile}" ]; then
    if grep -F "${user}" "${allowfile}" > /dev/null 2>&1; then
        echo "[+] ${allowfile} remains unchanged"
    else
        echo "${user}" >> "${allowfile}"
        chmod u=rw,g=r,o= "${allowfile}"
        if [ "$(uname)" = "OpenBSD" ]; then
            chgrp crontab "${allowfile}"
        fi
        echo "[+] ${allowfile} has changed. Please review the changes"
    fi
fi

if [ -e "${crontab}" ]; then
    yes | crontab -u "${user}" -r
fi
crontab -u "${user}" "${share}"/crontab
chmod u=rw,g=,o= "${crontab}"
echo "[+] ${crontab} installed"
