#!/bin/sh -e

##
# variables
localbase=$("$(dirname "$0")"/dirname "$0" 3)
share="${localbase}"/share/blocks+cron
doas=$(cat "${share}"/doas.conf)
doasfile=""

##
# main
# shellcheck disable=SC1091
if [ "$(uname)" = "OpenBSD" ]; then
    doasfile="/etc/doas.conf"
elif [ "$(uname)" = "FreeBSD" ]; then
    doasfile="${localbase}/etc/doas.conf"
else
    echo "[x] $(uname) is not supported"
    exit 1
fi

if grep -F "^${doas}$" "${doasfile}" > /dev/null 2>&1; then
    echo "[+] ${doasfile} remains unchanged"
else
    echo "${doas}" >> "${doasfile}"
    echo "[+] ${doasfile} has changed. Please review the changes"
fi
