#!/bin/sh -e

##
# variables
localbase=$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")
libexec="${localbase}"/libexec/blocks+cron
share="${localbase}"/share/blocks+cron

##
# main
# shellcheck disable=SC1091
. "${libexec}"/platform.sh
file=""
doas=$(cat "${share}"/doas.conf)
if isOpenBSD; then
    file="/etc/doas.conf"
elif isFreeBSD; then
    file="${LOCALBASE:-/usr/local}/etc/doas.conf"
fi
if grep -F "^${doas}$" "${file}" > /dev/null 2>&1; then
    echo "[-] ${file} remains unchanged"
else
    echo "${doas}" >> "${file}"
    echo "[-] ${file} has been changed. Please review the changes"
fi
