#!/bin/sh -e

##
# variables
user="_blocks"
localbase=$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")
homedir="${localbase}"/share/blocks+cron/home/"${user}"

##
# main
# shellcheck disable=SC1091
if ! id "${user}" > /dev/null 2>&1; then
    if [ "$(uname)" = "OpenBSD" ]; then
        useradd \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            "${user}"
        echo "[-] The ${user} user and group have been created"
    elif [ "$(uname)" = "FreeBSD" ]; then
        pw useradd \
            -s "/sbin/nologin" \
            -c "${user} user account" \
            -d "/home/${user}" \
            -mk "${homedir}" \
            -n "${user}"
        echo "[-] The ${user} user and group have been created"
    else
        echo "[x] $(uname) is not supported"
        exit 1
    fi
else
    if [ ! -e "/home/${user}" ]; then
        mkdir /home/${user}
    fi
    find "${homedir}" \
          -mindepth 1 \
          -maxdepth 1 \
          -exec cp -Rf {} /home/${user}/ \;
    echo "[-] The ${user} user exists"
fi

find /home/"${user}" \
    -type d \
    -exec chmod u=rwx,g=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -exec chmod u=rw,g=r,o= {} \;
find /home/"${user}"/.local/libexec \
    -type f \
    -exec chown root:_blocks {} \; \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}"/bin \
    -type f \
    -exec chown _blocks:_blocks {} \; \
    -exec chmod ug=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -name .gitkeep \
    -exec rm {} \;
