#!/bin/sh
set -e

##
# setup
. /home/_blocklist/.local/sh/today.sh
path="/home/_blocklist/blocklists/$(today)"

##
# main
chown root:_blocklist "${path}"
chmod u=rw,g=r,o= "${path}"
cp "${path}" /usr/local/share/pf/blocklist
