#!/bin/sh -e

##
# setup
. /home/_blocklist/.local/sh/today.sh
path="/home/_blocklist/blocks/$(today)"

##
# main
set -x
install -d \
    -o root \
    -g wheel \
    -m u=rwx,g=rwx,o= \
    "/usr/local/share/pf"
install -o root \
    -g _blocklist \
    -m u=rw,g=r,o= \
    "${path}" \
    "/usr/local/share/pf/blocklist"
