#!/bin/sh -e

##
# setup
# shellcheck source=/dev/null
. "/home/_blocklist/.local/sh/today.sh"
path="/home/_blocklist/blocks/$(today)"

##
# main
set -x
install -d \
    -o root \
    -g wheel \
    -m u=rwx,g=rx,o= \
    "/usr/local/share/pf"
install -o root \
    -g wheel \
    -m u=rw,g=r,o= \
    "${path}" \
    "/usr/local/share/pf/blocklist"
