.Dd May 2023
.Dt BLOCKLIST 8
.Os
.Sh NAME
.Nm blocklist
- common IPv4 blocklists as PF tables.
.Sh SYNOPSIS
.Nm blocklist download
.Nm blocklist echo
.Sh DESCRIPTION
.Nm blocklist
is a command line utility that can fetch common IPv4
blocklists, and from those blocklists create PF tables that can
be used when crafting firewall rules in
.Pa /etc/pf.conf .
.Pp
.Sh EXAMPLES
.Pp
.Nm blocklist download
.br
Download blocklists to ~/.local/share/blocklist/.
.Pp
.Nm blocklist echo
.br
Echo PF tables to standard output.
.Pp
.Sh AUTHORS
The
.Nm blocklist
utility and this manual page were written by
0x1eef <0x1eef@protonmail.com>.
