.Dd May 2023
.Dt BLOCKLIST 8
.Os
.Sh NAME
blocklist - common IPv4 blocklists as PF tables.
.Sh SYNOPSIS
blocklist download
.br
blocklist echo
.Sh DESCRIPTION
blocklist is a command line utility that can download
.br
common IPv4 blocklists, and from those blocklists create
.br
PF tables that can be used when crafting firewall rules
.br
in
.Pa /etc/pf.conf .
.Pp
.Sh EXAMPLES
.Pp
.Nm blocklist download
.br
Download blocklists to ~/.local/share/blocklist/.
.Pp
.Nm blocklist echo
.br
Echo PF tables to standard output.
.Pp
.Sh AUTHORS
The blocklist utility and this manual page were written
.br
by 0x1eef <0x1eef@protonmail.com>.
