#!/bin/sh
set -e

##
# variables
# shellcheck source=/dev/null
today=$(date "+%Y%m%d")
path="/home/_blocks/.local/share/blocks+cron/${today}"

##
# main
set -x
install -d \
    -o root \
    -g wheel \
    -m u=rwx,g=rx,o= \
    "/usr/local/share/pf"
install -o root \
    -g wheel \
    -m u=rw,g=r,o= \
    "${path}" \
    "/usr/local/share/pf/blocklist"
