#!/bin/sh
set -e

##
# variables
tables="attacks malware adware anonymizers"

##
# functions
printok() {
    printf "ok: %s\n" "${1}" > /dev/stdout
}

##
# main
/sbin/pfctl -nf /etc/pf.conf
for t in ${tables}; do
    pfctl -Tkill -t"${t}" > /dev/null 2>&1
    printok "kill table ${t}"
done
/sbin/pfctl -f/etc/pf.conf
printok "reload /etc/pf.conf"
