#!/bin/sh -e

##
# variables
user="_blocklist"
localbase=$(dirname $(dirname $(dirname $(realpath "$0"))))
libexec="${localbase}"/libexec/blocklist+cron
share="${localbase}"/share/blocklist+cron
homedir="${localbase}"/share/blocklist+cron/home/"${user}"

##
# main
. "${libexec}"/platform.sh
crontab="/var/cron/tabs/${user}"
if [ -e "${crontab}" ]; then
    yes | crontab -u "${user}" -r
fi
crontab -u "${user}" "${share}"/crontab
chmod u=rw,g=,o= "${crontab}"
echo "[-] New crontab: ${crontab}"

file=""
if isOpenBSD; then
    file="/var/cron/cron.allow"
elif isFreeBSD; then
    file="/var/cron/allow"
else
    echo "[-] Platform is not supported"
    exit 1
fi
if [ -e "${file}" ]; then
    if grep -F "${user}" "${file}" > /dev/null 2>&1; then
        echo "[-] ${file} remains unchanged"
    else
        echo "${user}" >> "${file}"
        chmod u=rw,g=r,o= "${file}"
        if isOpenBSD; then
            chgrp crontab "${file}"
        fi
        echo "[-] ${file} has been changed. Please review the changes"
    fi
fi
