#!/bin/sh -e

##
# variables
# shellcheck source=/dev/null
. "/home/_blocks/.local/sh/today.sh"
path="/home/_blocks/blocks/$(today)"

##
# main
set -x
install -d \
    -o root \
    -g wheel \
    -m u=rwx,g=rx,o= \
    "/usr/local/share/pf"
install -o root \
    -g wheel \
    -m u=rw,g=r,o= \
    "${path}" \
    "/usr/local/share/pf/blocklist"
