#!/bin/sh -e

##
# variables
# shellcheck source=/dev/null
tables="attacks malware anonymizers adware"

##
# main
pfctl -nf/etc/pf.conf
for table in ${tables}; do
    pfctl -Tkill -t"${table}"
done
pfctl -f/etc/pf.conf
